version: "3.9"
# Create a custom build that can be re-used within Docker network
x-build-iota-core: &iota-core_build
  context: ${DOCKER_BUILD_CONTEXT:-../../}
  dockerfile: ${DOCKERFILE_PATH:-./Dockerfile}
services:
  peer_master:
    build: *iota-core_build
    stop_grace_period: 1m
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.seed=0x88ce2019dd99fd5a3c46e10ffc192549fc4491eee07552153ff66cf792b6a0af
      --blockIssuer.rateSetterEnabled=true
      --blockIssuer.issuerAccount=0x907c02e9302e0f0571f10f885594e56d8c54ff0708ab7a39bc1b74d396b93b12
      --blockIssuer.privateKey=443a988ea61797651217de1f4662d4d6da11fd78e67f94511453bf6576045a05293dc170d9a59474e6d81cfba7f7d924c09b25d7166bcfba606e53114d0a758b
      --activity.ignoreBootstrapped=true
      --restAPI.allowIncompleteBlock=true
      --inx.enabled=true
      --inx.bindAddress=0.0.0.0:9029
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    ports:
      - "8080:8080/tcp" # web API
      - "8081:8081/tcp" # dashboard
      - "6081:6061/tcp" # pprof
      - "9029:9029/tcp" # inx
    networks:
      - iota-core

  inx-indexer:
    image: iotaledger/inx-indexer:2.0-alpha
    stop_grace_period: 1m
    command:
      - "--inx.address=peer_master:9029"
      - "--restAPI.bindAddress=inx-indexer:9091"
    networks:
      - iota-core

  peer_master2:
    image: docker-network-peer_master:latest
    stop_grace_period: 1m
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.seed=0xf739eea09eb0f4820f26504a3135131a075089b4c901c19c2099513ee016f516
      --blockIssuer.rateSetterEnabled=true
      --blockIssuer.issuerAccount=0x375358f92cc94750669598b0aaa55a6ff73310b90710e1fad524c0f911be0fea
      --blockIssuer.privateKey=3a5d39f8b60367a17fd54dac2a32c172c8e1fd6cf74ce65f1e13edba565f281705c1de274451db8de8182d64c6ee0dca3ae0c9077e0b4330c976976171d79064
      --restAPI.allowIncompleteBlock=true
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    ports:
      - "8070:8080/tcp" # web API
      - "8071:8081/tcp" # dashboard
      - "6071:6061/tcp" # pprof
    networks:
      - iota-core

  faucet:
    image: docker-network-peer_master:latest
    stop_grace_period: 1m
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.seed=0x2ab2792bba8ab6deb7978165e4072d3f00def97a0138b98ba2d21eba54159705
      --blockIssuer.rateSetterEnabled=true
      --blockIssuer.issuerAccount=0x6aee704f25558e8aa7630fed0121da53074188abc423b3c5810f80be4936eb6e
      --blockIssuer.privateKey=db39d2fde6301d313b108dc9db1ee724d0f405f6fde966bd776365bc5f4a5fb31e4b21eb51dcddf65c20db1065e1f1514658b23a3ddbf48d30c0efc926a9a648
      --restAPI.allowIncompleteBlock=true
    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    ports:
      - "8090:8080/tcp" # web API
      - "8091:8081/tcp" # dashboard
      - "6091:6061/tcp" # pprof
    networks:
      - iota-core

  peer_nomana:
    image: docker-network-peer_master:latest
    stop_grace_period: 1m
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.seed=0x6bd12a0398f9264788bc6481e2665eb90bd58a33b82347fb70f612cc8a91fcce
      --blockIssuer.issuerAccount=0xd057230f48fdf59ae093e2179857c590e960b05389399399ce69ad169a9c7f37
      --blockIssuer.privateKey=dcf7adb000f03826f1964a3e5378874b1972c38229fb740a8e47f2c421cddcf9a54fafa44a88e4a6a37796526ea884f613a24d84337871226eb6360f022d8b39
      --restAPI.allowIncompleteBlock=true
      --logger.level=debug

    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    ports:
      - "8040:8080/tcp" # web API
      - "8041:8081/tcp" # dashboard
      - "6041:6061/tcp" # pprof
    networks:
      - iota-core

  peer_nomana2:
    image: docker-network-peer_master:latest
    stop_grace_period: 1m
    command: >
      ${COMMON_CONFIG}
      ${MANUALPEERING_CONFIG}
      --p2p.seed=0x4da1119dc9cc3750ebb313c3c7dcb50120465544d256ee3c0d4586ce1772c96b
      --blockIssuer.issuerAccount=0x7a9ec5d9c0c145bae03b20cbe481cfea306e688c00525b410eb8cb18a169ed7f
      --blockIssuer.privateKey=0d8ecad4cefe927d2b6c64ee56576c52450f9a7a0113f96683cf8e8cc5c64264cb5ea14175ce649149ee41217c44aa70c3205b9939968449eae408727a71f91b
      --restAPI.allowIncompleteBlock=true

    volumes:
      - ./docker-network.snapshot:/app/data/snapshot.bin
      - ./config.json:/app/config.json:ro
    ports:
      - "8030:8080/tcp" # web API
      - "8031:8081/tcp" # dashboard
      - "6031:6061/tcp" # pprof
    networks:
      - iota-core

  prometheus:
    image: prom/prometheus:latest
    profiles:
      - grafana
    ports:
      - "9090:9090"
    command:
      - --config.file=/run/secrets/prometheus.yml
    secrets:
      - prometheus.yml
    networks:
      - iota-core
    depends_on:
      - peer_master

  grafana:
    image: grafana/grafana:9.5.6
    profiles:
      - grafana
    environment:
      - GF_ALERTING_ENABLED=true
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/local_dashboard.json
    networks:
      - iota-core
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/:ro

# Create our own network
networks:
  iota-core:
    driver: bridge
# Named Docker volumes for data persistence
volumes:
  grafana_data:
# read only files to load in the containers that may be shared across containers
secrets:
  prometheus.yml:
    file: ${PROMETHEUS_CONFIG:-./prometheus.yml}
