name: GolangCIlint

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - 'scripts/**'
      - 'tools/**'
jobs:
  golangci-lint:
    name: GolangCI-Lint
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Checkout custom linter
        uses: actions/checkout@v3
        with:
          repository: karimodm/typegroupingcheck
          path: typegroupingcheck 

      - name: Setup go
        uses: actions/setup-go@v4

      - name: Build custom linter
        working_directory: ./typegroupingcheck
        run: |
          go build -buildmode=plugin -o typegroupingcheck.so

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=10m"
          reporter: github-pr-check
          filter_mode: nofilter
          fail_on_error: true
